"""Description

Revision ID: 0045b1f94743
Revises: 072e3db21fe5
Create Date: 2024-04-27 12:22:33.819595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0045b1f94743'
down_revision = '072e3db21fe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
