"""Description

Revision ID: 072e3db21fe5
Revises: baa9097006be
Create Date: 2024-04-27 09:24:21.367138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072e3db21fe5'
down_revision = 'baa9097006be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.drop_index('ix_sneaker_brand_name', table_name='sneaker')
    op.drop_index('ix_sneaker_color', table_name='sneaker')
    op.drop_index('ix_sneaker_description', table_name='sneaker')
    op.drop_index('ix_sneaker_free_delivery', table_name='sneaker')
    op.drop_index('ix_sneaker_name', table_name='sneaker')
    op.drop_index('ix_sneaker_size', table_name='sneaker')
    op.drop_table('sneaker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sneaker',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('free_delivery', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sneaker_pkey')
    )
    op.create_index('ix_sneaker_size', 'sneaker', ['size'], unique=False)
    op.create_index('ix_sneaker_name', 'sneaker', ['name'], unique=False)
    op.create_index('ix_sneaker_free_delivery', 'sneaker', ['free_delivery'], unique=False)
    op.create_index('ix_sneaker_description', 'sneaker', ['description'], unique=False)
    op.create_index('ix_sneaker_color', 'sneaker', ['color'], unique=False)
    op.create_index('ix_sneaker_brand_name', 'sneaker', ['brand_name'], unique=False)
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
