"""Description

Revision ID: 223f324d0fcf
Revises: b75b25de6b28
Create Date: 2024-04-27 12:52:11.514582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223f324d0fcf'
down_revision = 'b75b25de6b28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
