"""Description

Revision ID: 721870b8d065
Revises: 1f41583738f4
Create Date: 2024-04-27 12:42:26.106148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721870b8d065'
down_revision = '1f41583738f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
