"""Description

Revision ID: a0691d5830ed
Revises: 223f324d0fcf
Create Date: 2024-04-27 12:55:38.428725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0691d5830ed'
down_revision = '223f324d0fcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
