"""Description

Revision ID: b75b25de6b28
Revises: 721870b8d065
Create Date: 2024-04-27 12:44:52.773063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75b25de6b28'
down_revision = '721870b8d065'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
